### ISSUE TITLE
Random seed initialized at compile time 

### ISSUE THREAD

**Issue by xerz-one** [gluonhq/gluonfx-maven-plugin#102]
Despite GraalVM having apparently fixed this issue (https://github.com/oracle/graal/issues/1610), compiling a program that uses e.g. `Math.random()` will always return the same numbers, seemingly due to generating the seed at compile time. Manually creating a new seed using `java.util.Random` does fix the issue.

**Comment by jperedadnr** [comment]
This shouldn't be an issue anymore with the latest plugin 1.0.10. Feel free to reopen otherwise (but this should be reported to the GraalVM issue tracker).
