### ISSUE TITLE
Use of system menubar not possible

### ISSUE THREAD

**Issue by lanthale** [gluonhq/gluonfx-maven-plugin#11]
I am using in my sample application "menubar.setUseSystemMenuBar(true);" to use the system menu on top. But it is not working with the plugin and there are some artefact if you click one menu.

**Comment by jperedadnr** [comment]
Thanks for reporting. I can reproduce the issue.

**Comment by jperedadnr** [comment]
Can you try this:

```
gluonClient {
    ...
    javafxStaticSdkVersion = "13-ea+6"
    ...
}
```

**Comment by lanthale** [comment]
I have tried now. It is much better but the menu has not changed to the top. But the small grafic issues are now much more minimized. So therefore an big improvment in contrast to before.

**Comment by jperedadnr** [comment]
See https://github.com/gluonhq/substrate/issues/118#issuecomment-569533473 for an explanation. I'm closing this issue as it will be solved as part of https://github.com/gluonhq/substrate/issues/118
