### ISSUE TITLE
.app bundle for macOS

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/gluonfx-maven-plugin#117]
In contrast to what the [documentation](https://docs.gluonhq.com/client/#_macos) says, the command `mvn client:build` does not produce an .app bundle for macOS. The output is just an executable file. I also tried `mvn client:package`, but that does not seem to have any effect at all.

So, what is currently the recommended way to produce such a bundle and is it planned to re-establish the behavior described in the docs?

**Comment by mipastgt** [comment]
I see the documentation has been updated but I think there is a bug in there.
"macOS - app, pkg, deb" should probably read "macOS - app, pkg, dmg" instead.
So it looks as if you are planning to use the jpackage tool for packaging of the desktop platforms, right?

**Comment by jperedadnr** [comment]
Fixed docs, and plugin already creates .app, .pkg, and .dmg bundles (this one still under 1.0.11-SNAPSHOT).
