### ISSUE TITLE
Getting JAXB to work

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/gluonfx-maven-plugin#130]
Getting JAXB to work in a native image is not an easy task. See e.g. here: https://github.com/oracle/graal/issues/379 The conclusion there is that this will be only supported via the tracing agent. With a separate test program I succeeded to get that working according to the description given in the above reference. When I tried to manually apply the result to the client-maven-plugin I realized that for this I would need to add a proxyList but, at least according to the documentation, the client-maven-plugin does not support such a list. This is a missing feature and should be added. (Even better would be to integrate the output of the tracing agent directly.)

**Comment by lazar-mitrovic** [comment]
You might be able to work around that issue by providing 
`/src/main/resources/META-INF/native-image/proxy-config.json`
`/src/main/resources/META-INF/native-image/reflect-config.json`

Or if you prefer command line approach you could use `nativeImageArgs` like
```
<nativeImageArgs>
    <list>-agentlib:native-image-agent=config-output-dir=$CONFIG_DIR,caller-filter-file=$FILTER_FILE_PATH</list>
    <list>--verbose</list>
</nativeImageArgs>
```

**Comment by mipastgt** [comment]
@lazar-mitrovic Thanks for the input. What you describe in the comment to #119 is basically what I already did with my above mentioned test program. So I know how to get that running with native-image. The problem is the client-maven-plugin which creates its on lists, overwriting others, merging these with other user input and then forward that to native-image. 1. What I do not know is what the right way would be to add the missing information so that I can be sure it is really picked up and not ignored or overwritten. 2. I was asking for a real future proof solution for this problem because it must be possible to provide these proxies in some official way.

**Comment by jperedadnr** [comment]
`mvn gluonfx:runagent` should be enough now.
