### ISSUE TITLE
Plugin hangs forever or even crashes with new version 0.1.16

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/gluonfx-maven-plugin#136]
I just tried the new plugin version 0.1.16 but this new release is completely unusable for me. Even after a long time of waiting I did not get any result. It is also curious that the process, after some initial work, later did not show any activity anymore. It is just silent but does not finish. I guess this is due to the switch to --no-server because some time ago I played with that option myself and got the same result. So I immediately switched back to the default. I don't know exactly what the technical difference between these two modes is and what your motivation was to do the switch but at least it does not work at all for me and there does not seem to be any possibility for me to negate this change.

See also: https://github.com/gluonhq/substrate/issues/375

macOS 10.14.6
GraalVM 20.0.0
client-maven-plugin 0.1.16
jfx 15-ea+1

**Comment by jperedadnr** [comment]
Can you do the following:
- Clone Substrate, remove the `--no-server` flag, build and publish locally (`./gradlew clean publishToMavenLocal`)
- Clone client-maven-plugin, build and publish locally (`mvn clean install`)
- Run your HelloFX sample with this `0.1.17-SNAPSHOT` version and see if that makes a difference?

**Comment by mipastgt** [comment]
I just did what you asked me to do. After that building my application worked as before. It took 07:40 min (roughly the same time as before) and the resulting binary also worked as before. I can send you the output log if you like but I veryfied that it actually used the newly built 0.1.17-SNAPSHOT release. So, at least for larger projects, the --no-server flag is a killer.

**Comment by mipastgt** [comment]
Just an update on client-maven-plugin 0.1.18 and graalvm-svm-darwin-20.1.0-ea+26.
With this new release I am able again to build the smaller variant of my application. I could not test the full variant because the build fails. This full variant uses JAXB and it seems I got hit by this issue: https://github.com/oracle/graal/issues/2169 Maybe you can provide a new build of your private graalvm once this bug is definitely fixed, so that I can test the full build again.

**Comment by johanvos** [comment]
To clarify: we are now using 100% the latest code from https://github.com/oracle/graal in our builds. All changes that we required are upstreamed. Hence, whenever an issue is fixed upstream in oracle/graal, it will be fixed the next day in our daily builds too.

The difference between our builds and the upstream builds is that we include the clibraries for the android/ios platforms -- but the plan is that this will be provided by upstream as well, so there will no need to use our build anymore.

**Comment by mipastgt** [comment]
Thanks for the clarification. That is good to know. Is the documentation then also updated daily, so that you can get a valid download link?

**Comment by mipastgt** [comment]
Hi Johan,
maybe I misunderstood your clarification above but now, almost three weeks later, the download link for your version of graal is still the same. (https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-darwin-20.1.0-ea+26.zip) Can you tell me where I can find these daily builds you were talking about? The only link I have is the one above and I would like to give this issue another try.

**Comment by jperedadnr** [comment]
This shouldn't be an issue anymore. Feel free to reopen otherwise.
