### ISSUE TITLE
Netbeans shows error's after adding plugin and mark all javafx releated files with errors

### ISSUE THREAD

**Issue by lanthale** [gluonhq/gluonfx-maven-plugin#151]
After apply the plugin netbeans get's confused and mark's all javafx files (references to javafx classes) as error with the message:
"package javafx.Application is not visible (package javafx.Application is declared in unnamend module but module javafx.Application does not read it)".

After removing the plugin the error's no longer disappearing. But "build/clean" is working as expected.

**Comment by jperedadnr** [comment]
Closing as not an issue. Feel free to reopen if the current version of the plugin (1.0.10) still fails for you.
