### ISSUE TITLE
VM option for fallback image

### ISSUE THREAD

**Issue by rsik88** [gluonhq/gluonfx-maven-plugin#163]
I have a fairly large JavaFX application and would like to see it has native image. Build went well but it failed to load image. The app has dependency on reflection in different modules which I worked around it using VM options like --add-opens.  
Of cause I would like to have a no fallback image, but I don't see how I can disable it with client. At this point, I would be happy to see subtrate VM takes the vm option and opens up the modules to reflection as temporary work around.

Any help is appreciated, or some directions and I am willing to put sometime to try a fix myself.

**Comment by jperedadnr** [comment]
vm options for the native image can be set, as well as runtime arguments, see [docs](https://docs.gluonhq.com/#_gluonfx_plugin_for_maven) for the most up to date plugin information. About reflection, you can use now `mvn gluonfx:runagent`.
