### ISSUE TITLE
Impossible to build a native-image with incomplete classpath

### ISSUE THREAD

**Issue by kristofdho** [gluonhq/gluonfx-maven-plugin#200]
The `jniconfig-x86_64-windows.json` file contains the entry
```json
  {
    "name" : "java.lang.Object",
    "methods" : [
      {"name":"<init>","parameterTypes":[] }
    ]
  }
```
This causes the native-image process to search for any subclass which also has the `<init>` method, using this snippet:

https://github.com/oracle/graal/blob/96acfe6701ff93e518b3b0bf8a21635d9613263c/substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/access/JNIAccessibleMethod.java#L138-L145
```java
private boolean anyMatchIgnoreReturnType(ResolvedJavaType sub) {
    for (ResolvedJavaMethod method : sub.getDeclaredMethods()) {
        if (descriptor.matchesIgnoreReturnType(method)) {
            return true;
        }
    }
    return false;
}
```

This forces all methods to be loaded in, including the ones with references to classes not on the classpath, which crashes the image building.

This is somewhat but not entirely related to https://github.com/oracle/graal/issues/2207

But the main question is, is the config for java.lang.Object <init> really required, as it forces a very broad restriction onto the entire build graph.

**Comment by sgyeme** [comment]
I am also stuck on the same issue native-image-maven-plugin is able to compile when some classes used are not on class path.I think it is the way linking is done with client-maven-plugin. I have been playing with spring-graal-native samples native-image-maven-plugin works fine but client-maven-plugin fails wth java.lang.NoClassDefFoundError

https://github.com/oracle/graal/tree/master/substratevm/src/native-image-maven-plugin

**Comment by jperedadnr** [comment]
Object was removed from the jni config file: https://github.com/gluonhq/substrate/pull/861/files#diff-b219792973b86abb2ab1797d682daaf4055516fd65bce999337f01e4c36eac5bL67
(and then only the `getClass` method was added). It shouldn't be an issue now anyway, but feel free to reopen if needed.
