### ISSUE TITLE
Unsupported ChipID value for QGPU features

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/gluonfx-maven-plugin#217]
After installing and running my Android app on my Samsung Galaxy Tab S4 with Android 10 I get many of the following strange warnings.

`D/GraalCompiled(15454): Warning: Unsupported ChipID value for QGPU features (0x5040001), using a5x as default.`

These warnings only show up for the first run after a fresh install and they do not show up at all on my Samsung Galaxy S7 phone with Android 8. I haven't noticed any bad consequences on the tablet but maybe these warnings hint to some underlying problem.

Here is a little more context:
[Unsupported ChipID value.zip](https://github.com/gluonhq/client-maven-plugin/files/4977420/Unsupported.ChipID.value.zip)

**Comment by jperedadnr** [comment]
I've only found this related [issue](https://github.com/XCSoar/XCSoar/issues/366). Not sure it applies to your case, but can you verify your min SDK?

**Comment by mipastgt** [comment]
In an oder version of my app I had min and max versions set but which recently updated all my stuff I copied the manifest which you generated and just added a few more permissions. The generated manifest does not contain any min and max versions anymore.

**Comment by jperedadnr** [comment]
In `target/client/aarch64-android/gvm/android_project` you have a full gradle project that you can play with. But the `app/build.gradle` file already sets `minSdkVersion' to 21 by default, so if you didn't set a lower value it will use that. Alternatively, you can copy the `AndroidManifest.xml` file into `src/android`, and add it directly.

**Comment by mipastgt** [comment]
I am happy with everything <= 26, that's why I left the default.

**Comment by jperedadnr** [comment]
Closing as not an issue anymore. Feel free to reopen otherwise.
