### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: cannot locate symbol "JVM_LatestUserDefinedLoader"

### ISSUE THREAD

**Issue by LeroyChristopherDunn** [gluonhq/gluonfx-maven-plugin#246]
Hi there

My client run task with android target fails with the below link error:

`E/AndroidRuntime( 5364): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "JVM_LatestUserDefinedLoader" referenced by "/data/app/hello.hellodesktop-iBjrZAkkXRerMNti0Voy9A==/lib/arm64/libsubstrate.so"...`

This specifically occurs when launching our enterprise jar with [Assisted Configuration of Native Image Builds](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) and I'm unfortunately unable to replicate the issue in a simple project

Could be related to [this issue](https://github.com/oracle/graal/issues/2451) or [this issue](https://github.com/spring-projects-experimental/spring-graalvm-native/issues/11) but our project uses neither Spring nor Docker and the issue occurs at run time not build time

Env:
GraalVM 20.2.0 and it's bundled Java 11
Ubuntu 16.04
Maven client plugin version 0.1.31

Logs
[full-stacktrace.log](https://github.com/gluonhq/client-maven-plugin/files/5130019/full-stacktrace.log)

jdeps output of our jar
[dependencies.txt](https://github.com/gluonhq/client-maven-plugin/files/5130011/dependencies.txt)

No native libraries are extracted ( `target/client/aarch64-android/gvm/lib` folder is empty)

Any assistance would be greatly appreciated

**Comment by jperedadnr** [comment]
The use of `latestUserDefinedLoader` comes from https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/jdk/internal/misc/VM.java#L359. This method is used by `ObjectInputStream::resolveClass` that uses an `ObjectStreamClass` class, which extends from `Serializable`. However, serialization is not supported by GraalVM.

Have you built the native image and run it on desktop? Did it work fine?
Can you search for uses of  `ObjectInputStream::resolveClass` in your project?

**Comment by LeroyChristopherDunn** [comment]
Thanks. We do use serialization in our project. I'll work on removing it before trying GraalVM again - on desktop first then mobile

**Comment by jperedadnr** [comment]
Serialization is supported now by GraalVM. Update to latest plugin and GraalVM, and run `mvn gluonfx:runagent` to get the required configuration files.
