### ISSUE TITLE
memory flags

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/gluonfx-maven-plugin#295]
### Expected Behavior
memory flags 

### Current Behavior
If i run the compiled app, GC doesnt work and it eats away all the memory of my phone and eventually crashes. Settings -Xmx, -Xms fixes it, but I dont see an option to do the same with the gluon client plugin (My app uses a lot of Gifs)

**Comment by rnayabed** [comment]
https://github.com/oracle/graal/issues/1109#issuecomment-475900206

**Comment by jperedadnr** [comment]
The gradle project created in the gluonfx:package step has a [gradle.properties](https://github.com/gluonhq/substrate/blob/master/src/main/resources/native/android/android_project/gradle.properties#L4) file with those settings.
You can modify the file once it is created, and then manually build the apk with `./gradlew assembleRelease`.
