### ISSUE TITLE
Ubuntu: if libgtk 3 not installed, client:link fails with /usr/bin/ld: cannot find -lgtk-3

### ISSUE THREAD

**Issue by AlmasB** [gluonhq/gluonfx-maven-plugin#32]
`apt-get install libgtk-3-dev` fixes it. I don't know if other packages (i.e. w/o -dev suffix) could fix it. Suggest adding this to Readme.

**Comment by johanvos** [comment]
Interesting remark. JavaFX on linux currently supports both gtk3 and gtk2, so we could do it here as well. What Linux distribution are you using?

**Comment by AlmasB** [comment]
Ubuntu 16.04

**Comment by jperedadnr** [comment]
This shouldn't be an issue anymore with a recent version of the plugin. Feel free to reopen otherwise.
