### ISSUE TITLE
Compiled app on Win10 crashes with result code -1073741819

### ISSUE THREAD

**Issue by bgmf** [gluonhq/gluonfx-maven-plugin#321]
I've managed to compile a rather large legacy application on Linux and wanted to expand this to other platforms.
Compilation is successful, but the app crashes immediatly when started.

There's a lot of stuff added to compile SQLite into the app, so I needed to adjust JNI and resource config as well as adding a specific GraalVM `@AutomaticFeature`.

The result code -1073741819 lead me to [this StackOverflow question](https://stackoverflow.com/questions/62503113/graalvm-exe-file-compiled-with-gluon-client-maven-plugin-crashes-with-result-1), but I couldn't find an issue related to it...

<details>
<summary><b>\target\client\log\process-run until end-1621417294463.log</b></summary>
<pre><code>
Process
=======
run until end

Command Line
============
C:\Users\dzimmermann\git\performance\speedtest_app\target\client\x86_64-windows\cnlab Speed Test.exe

Output
======
Main
2021-05-19 11:41:32.228;INFO;[34mmain[m;[37mch.cnlab.performanceapplet.fx.util.SingleInstanceHelper[m.[36minit[m(SingleInstanceHelper.java:[36m39[m);Using Lockfile @ C:\Users\DZIMME~1\AppData\Local\Temp\cnlabUX.lock
2021-05-19 11:41:32.228;INFO;[34mmain[m;[37mch.cnlab.performanceapplet.fx.util.SingleInstanceHelper[m.[36mlock[m(SingleInstanceHelper.java:[36m72[m);single instance locked
May 19, 2021 11:41:32 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @383e21'

Result
======
result: -1073741819
</code></pre>
</details>

<details>
<summary><b>WinDbg output</b></summary>
<pre><code>
CommandLine: C:\Users\dzimmermann\git\performance\speedtest_app\target\client\x86_64-windows\cnlabUX.exe
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff7`92720000 00007ff7`9973a000   cnlabUX.exe
ModLoad: 00007ffe`83950000 00007ffe`83b45000   ntdll.dll
ModLoad: 00007ffe`83500000 00007ffe`835bd000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ffe`810f0000 00007ffe`813b8000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007ffe`81c90000 00007ffe`81d3c000   C:\WINDOWS\System32\ADVAPI32.dll
ModLoad: 00007ffe`82b00000 00007ffe`82b9e000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 00007ffe`82210000 00007ffe`822ab000   C:\WINDOWS\System32\sechost.dll
ModLoad: 00007ffe`82580000 00007ffe`826ab000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 00007ffe`82510000 00007ffe`8257b000   C:\WINDOWS\System32\WS2_32.dll
ModLoad: 00007ffe`80f90000 00007ffe`80fbe000   C:\WINDOWS\SYSTEM32\USERENV.dll
ModLoad: 00007ffe`79570000 00007ffe`7957a000   C:\WINDOWS\SYSTEM32\VERSION.dll
ModLoad: 00007ffe`82a20000 00007ffe`82afa000   C:\WINDOWS\System32\COMDLG32.dll
ModLoad: 00007ffe`81760000 00007ffe`81860000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007ffe`826c0000 00007ffe`82a15000   C:\WINDOWS\System32\combase.dll
ModLoad: 00007ffe`82420000 00007ffe`824ce000   C:\WINDOWS\System32\shcore.dll
ModLoad: 00007ffe`83770000 00007ffe`83910000   C:\WINDOWS\System32\USER32.dll
ModLoad: 00007ffe`81980000 00007ffe`819a2000   C:\WINDOWS\System32\win32u.dll
ModLoad: 00007ffe`822b0000 00007ffe`822da000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 00007ffe`814c0000 00007ffe`815cb000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 00007ffe`818e0000 00007ffe`8197d000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 00007ffe`819b0000 00007ffe`81a05000   C:\WINDOWS\System32\SHLWAPI.dll
ModLoad: 00007ffe`82c20000 00007ffe`83362000   C:\WINDOWS\System32\SHELL32.dll
ModLoad: 00007ffe`75da0000 00007ffe`75e50000   C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.844_none_423537bff6b9828c\COMCTL32.dll
ModLoad: 00007ffe`824d0000 00007ffe`82500000   C:\WINDOWS\System32\IMM32.dll
ModLoad: 00007ffe`83370000 00007ffe`8349a000   C:\WINDOWS\System32\ole32.dll
ModLoad: 00007ffe`7e8c0000 00007ffe`7e8ef000   C:\WINDOWS\SYSTEM32\dwmapi.dll
ModLoad: 00007ffe`81b30000 00007ffe`81bfd000   C:\WINDOWS\System32\OLEAUT32.dll
ModLoad: 00007ffe`59b50000 00007ffe`59e45000   C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL
ModLoad: 00007ffe`78450000 00007ffe`7863e000   C:\WINDOWS\SYSTEM32\urlmon.dll
ModLoad: 00007ffe`6e130000 00007ffe`6e157000   C:\WINDOWS\SYSTEM32\WINMM.dll
ModLoad: 00007ffe`80870000 00007ffe`808da000   C:\WINDOWS\SYSTEM32\MSWSOCK.dll
ModLoad: 00007ffe`41370000 00007ffe`41401000   C:\WINDOWS\SYSTEM32\MSVCP140.dll
ModLoad: 00007ffe`41a50000 00007ffe`41a69000   C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
ModLoad: 00007ffe`665f0000 00007ffe`665fc000   C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
ModLoad: 00007ffe`80510000 00007ffe`8054b000   C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00007ffe`79360000 00007ffe`7936c000   C:\WINDOWS\SYSTEM32\Secur32.dll
ModLoad: 00007ffe`77ee0000 00007ffe`78190000   C:\WINDOWS\SYSTEM32\iertutil.dll
ModLoad: 00007ffe`7e0e0000 00007ffe`7e1d7000   C:\WINDOWS\SYSTEM32\PROPSYS.dll
ModLoad: 00007ffe`80f50000 00007ffe`80f81000   C:\WINDOWS\SYSTEM32\SSPICLI.DLL
(3a28.3280): Break instruction exception - code 80000003 (first chance)
ntdll!LdrpDoDebuggerBreak+0x30:
00007ffe`83a20770 cc              int     3
0:000> bt
        ^ Operation not supported in current debug session 'bt'
0:000> gn
ModLoad: 00007ffe`80fd0000 00007ffe`80fef000   C:\WINDOWS\SYSTEM32\profapi.dll
ModLoad: 00007ffe`7faa0000 00007ffe`7fab2000   C:\WINDOWS\SYSTEM32\kernel.appcore.dll
ModLoad: 00007ffe`74db0000 00007ffe`74dc7000   C:\WINDOWS\system32\napinsp.dll
ModLoad: 00007ffe`74ed0000 00007ffe`74eeb000   C:\WINDOWS\system32\pnrpnsp.dll
ModLoad: 00007ffe`7c4e0000 00007ffe`7c4f5000   C:\WINDOWS\system32\wshbth.dll
ModLoad: 00007ffe`7a970000 00007ffe`7a98d000   C:\WINDOWS\system32\NLAapi.dll
ModLoad: 00007ffe`80560000 00007ffe`8062c000   C:\WINDOWS\SYSTEM32\DNSAPI.dll
ModLoad: 00007ffe`82500000 00007ffe`82508000   C:\WINDOWS\System32\NSI.dll
ModLoad: 00007ffe`751f0000 00007ffe`75202000   C:\WINDOWS\System32\winrnr.dll
ModLoad: 00007ffe`7acd0000 00007ffe`7acda000   C:\Windows\System32\rasadhlp.dll
ModLoad: 00007ffe`7bf40000 00007ffe`7bfbf000   C:\WINDOWS\System32\fwpuclnt.dll
ModLoad: 00007ffe`81730000 00007ffe`81757000   C:\WINDOWS\System32\bcrypt.dll
ModLoad: 00000221`33800000 00000221`33803000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-console-l1-1-0.dll
ModLoad: 00000221`33800000 00000221`33803000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-console-l1-1-0.dll
ModLoad: 00000221`33810000 00000221`33813000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-datetime-l1-1-0.dll
ModLoad: 00000221`33810000 00000221`33813000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-datetime-l1-1-0.dll
ModLoad: 00000221`352d0000 00000221`352d3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-debug-l1-1-0.dll
ModLoad: 00000221`352d0000 00000221`352d3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-debug-l1-1-0.dll
ModLoad: 00000221`352e0000 00000221`352e3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-errorhandling-l1-1-0.dll
ModLoad: 00000221`352e0000 00000221`352e3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-errorhandling-l1-1-0.dll
ModLoad: 00000221`352f0000 00000221`352f4000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-file-l1-1-0.dll
ModLoad: 00000221`352f0000 00000221`352f4000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-file-l1-1-0.dll
ModLoad: 00000221`35300000 00000221`35303000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-file-l1-2-0.dll
ModLoad: 00000221`35300000 00000221`35303000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-file-l1-2-0.dll
ModLoad: 00000221`35310000 00000221`35313000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-file-l2-1-0.dll
ModLoad: 00000221`35310000 00000221`35313000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-file-l2-1-0.dll
ModLoad: 00000221`35320000 00000221`35323000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-handle-l1-1-0.dll
ModLoad: 00000221`35320000 00000221`35323000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-handle-l1-1-0.dll
ModLoad: 00000221`35330000 00000221`35333000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-heap-l1-1-0.dll
ModLoad: 00000221`35330000 00000221`35333000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-heap-l1-1-0.dll
ModLoad: 00000221`35340000 00000221`35343000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-interlocked-l1-1-0.dll
ModLoad: 00000221`35340000 00000221`35343000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-interlocked-l1-1-0.dll
ModLoad: 00000221`35350000 00000221`35353000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-libraryloader-l1-1-0.dll
ModLoad: 00000221`35350000 00000221`35353000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-libraryloader-l1-1-0.dll
ModLoad: 00000221`35360000 00000221`35363000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-localization-l1-2-0.dll
ModLoad: 00000221`35360000 00000221`35363000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-localization-l1-2-0.dll
ModLoad: 00000221`35370000 00000221`35373000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-memory-l1-1-0.dll
ModLoad: 00000221`35370000 00000221`35373000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-memory-l1-1-0.dll
ModLoad: 00000221`3a940000 00000221`3a943000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-namedpipe-l1-1-0.dll
ModLoad: 00000221`3a940000 00000221`3a943000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-namedpipe-l1-1-0.dll
ModLoad: 00000221`3a950000 00000221`3a953000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-processenvironment-l1-1-0.dll
ModLoad: 00000221`3a950000 00000221`3a953000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-processenvironment-l1-1-0.dll
ModLoad: 00000221`3a960000 00000221`3a963000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-processthreads-l1-1-0.dll
ModLoad: 00000221`3a960000 00000221`3a963000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-processthreads-l1-1-0.dll
ModLoad: 00000221`3a970000 00000221`3a973000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-processthreads-l1-1-1.dll
ModLoad: 00000221`3a970000 00000221`3a973000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-processthreads-l1-1-1.dll
ModLoad: 00000221`3a980000 00000221`3a983000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-profile-l1-1-0.dll
ModLoad: 00000221`3a980000 00000221`3a983000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-profile-l1-1-0.dll
ModLoad: 00000221`3a990000 00000221`3a993000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-rtlsupport-l1-1-0.dll
ModLoad: 00000221`3a990000 00000221`3a993000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-rtlsupport-l1-1-0.dll
ModLoad: 00000221`3a9a0000 00000221`3a9a3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-string-l1-1-0.dll
ModLoad: 00000221`3a9a0000 00000221`3a9a3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-string-l1-1-0.dll
ModLoad: 00000221`3a9b0000 00000221`3a9b3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-synch-l1-1-0.dll
ModLoad: 00000221`3a9b0000 00000221`3a9b3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-synch-l1-1-0.dll
ModLoad: 00000221`3a9c0000 00000221`3a9c3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-synch-l1-2-0.dll
ModLoad: 00000221`3a9c0000 00000221`3a9c3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-synch-l1-2-0.dll
ModLoad: 00000221`3a9d0000 00000221`3a9d3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-sysinfo-l1-1-0.dll
ModLoad: 00000221`3a9d0000 00000221`3a9d3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-sysinfo-l1-1-0.dll
ModLoad: 00000221`3a9e0000 00000221`3a9e3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-timezone-l1-1-0.dll
ModLoad: 00000221`3a9e0000 00000221`3a9e3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-timezone-l1-1-0.dll
ModLoad: 00000221`3a9f0000 00000221`3a9f3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-util-l1-1-0.dll
ModLoad: 00000221`3a9f0000 00000221`3a9f3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-core-util-l1-1-0.dll
ModLoad: 00000221`3aa00000 00000221`3aa03000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-conio-l1-1-0.dll
ModLoad: 00000221`3aa00000 00000221`3aa03000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-conio-l1-1-0.dll
ModLoad: 00000221`3aa10000 00000221`3aa14000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-convert-l1-1-0.dll
ModLoad: 00000221`3aa10000 00000221`3aa14000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-convert-l1-1-0.dll
ModLoad: 00000221`3aa20000 00000221`3aa23000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-environment-l1-1-0.dll
ModLoad: 00000221`3aa20000 00000221`3aa23000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-environment-l1-1-0.dll
ModLoad: 00000221`3aa30000 00000221`3aa33000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-filesystem-l1-1-0.dll
ModLoad: 00000221`3aa30000 00000221`3aa33000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-filesystem-l1-1-0.dll
ModLoad: 00000221`3aa40000 00000221`3aa43000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-heap-l1-1-0.dll
ModLoad: 00000221`3aa40000 00000221`3aa43000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-heap-l1-1-0.dll
ModLoad: 00000221`3aa50000 00000221`3aa53000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-locale-l1-1-0.dll
ModLoad: 00000221`3aa50000 00000221`3aa53000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-locale-l1-1-0.dll
ModLoad: 00000221`3ac60000 00000221`3ac65000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-math-l1-1-0.dll
ModLoad: 00000221`3ac60000 00000221`3ac65000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-math-l1-1-0.dll
ModLoad: 00000221`3ac70000 00000221`3ac75000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-multibyte-l1-1-0.dll
ModLoad: 00000221`3ac70000 00000221`3ac75000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-multibyte-l1-1-0.dll
ModLoad: 00000221`3ac80000 00000221`3ac90000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-private-l1-1-0.dll
ModLoad: 00000221`3ac80000 00000221`3ac90000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-private-l1-1-0.dll
ModLoad: 00000221`3ac90000 00000221`3ac93000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-process-l1-1-0.dll
ModLoad: 00000221`3ac90000 00000221`3ac93000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-process-l1-1-0.dll
ModLoad: 00000221`3aca0000 00000221`3aca4000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-runtime-l1-1-0.dll
ModLoad: 00000221`3aca0000 00000221`3aca4000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-runtime-l1-1-0.dll
ModLoad: 00000221`3acb0000 00000221`3acb4000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-stdio-l1-1-0.dll
ModLoad: 00000221`3acb0000 00000221`3acb4000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-stdio-l1-1-0.dll
ModLoad: 00000221`3acc0000 00000221`3acc4000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-string-l1-1-0.dll
ModLoad: 00000221`3acc0000 00000221`3acc4000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-string-l1-1-0.dll
ModLoad: 00000221`3acd0000 00000221`3acd3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-time-l1-1-0.dll
ModLoad: 00000221`3acd0000 00000221`3acd3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-time-l1-1-0.dll
ModLoad: 00000221`3ace0000 00000221`3ace3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-utility-l1-1-0.dll
ModLoad: 00000221`3ace0000 00000221`3ace3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\api-ms-win-crt-utility-l1-1-0.dll
ModLoad: 00007ffe`72ba0000 00007ffe`72bc3000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\prism_d3d.dll
ModLoad: 00007ffe`41af0000 00007ffe`41cbe000   C:\WINDOWS\system32\d3d9.dll
ModLoad: 00007ffe`7f1c0000 00007ffe`7f950000   C:\WINDOWS\SYSTEM32\windows.storage.dll
ModLoad: 00007ffe`80b00000 00007ffe`80b2c000   C:\WINDOWS\SYSTEM32\Wldp.dll
ModLoad: 00007ffe`7e6f0000 00007ffe`7e78e000   C:\WINDOWS\system32\uxtheme.dll
ModLoad: 00007ffe`6ddd0000 00007ffe`6dfab000   C:\WINDOWS\System32\DriverStore\FileRepository\c0337713.inf_amd64_14492f689cec6971\B337386\aticfx64.dll
ModLoad: 00007ffe`5afa0000 00007ffe`5afd1000   C:\WINDOWS\System32\DriverStore\FileRepository\c0337713.inf_amd64_14492f689cec6971\B337386\atiu9p64.dll
ModLoad: 00007ffe`4eab0000 00007ffe`4f7f6000   C:\WINDOWS\System32\DriverStore\FileRepository\c0337713.inf_amd64_14492f689cec6971\B337386\atiumd64.dll
ModLoad: 00000000`5d350000 00000000`5e046000   C:\WINDOWS\System32\DriverStore\FileRepository\c0337713.inf_amd64_14492f689cec6971\B337386\atiumd6a.dll
ModLoad: 00007ffe`80630000 00007ffe`8067b000   C:\WINDOWS\SYSTEM32\POWRPROF.dll
ModLoad: 00007ffe`804f0000 00007ffe`80502000   C:\WINDOWS\SYSTEM32\UMPDC.dll
ModLoad: 00007ffe`72b50000 00007ffe`72b95000   C:\Program Files\BellSoft\LibericaJDK-11-Full\bin\glass.dll
(3a28.1908): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
cnlabUX!Java_com_sun_glass_ui_win_WinGestureSupport__1initIDs+0x246:
00007ff7`95413226 488b01          mov     rax,qword ptr [rcx] ds:00000000`00000000=????????????????
</code></pre>
</details>

As mentioned in other issues: I'm not very versed with native stuff, so that's basically a blackbox.
But: I was wondering if the issue mayby lie in the fact, that the build is somehow still trying to access my local BellSoft JDK libraries.

GraalVM version: graalvm-svm-windows-gluon-21.1.0-dev (downloaded yesterday)
JavaFX version: 16
Client plugin version: 0.1.39

Cheers,
Daniel

**Comment by bgmf** [comment]
Update: The idea with the other JDK seemed to be the correct idea. I checked my `%PATH%` and it was present. When I removed it and rebuild and linked the app I could start it.
Maybe it's a problem worth noting in the documentation. What do you think?

**Comment by tiainen** [comment]
Just to make things clear:

- where did the GRAALVM_HOME environment variable point to
- was the JAVA_HOME environment variable defined, and if so, where did it point to
- you had a "regular" JDK installation in your PATH environment variable, I would presume running `java -version` would then call the BellSoft JDK

**Comment by bgmf** [comment]
* GRAALVM_HOME pointed to a local directory containing the gluon variant of graalvm.  
* JAVA_HOME is present and I set it to point to the same location as GRAALVM_HOME.  
* I guess so, but I have removed it from PATH since then.

**Comment by jan-tosovsky-cz** [comment]
I can confirm what @bgmf stated: another JDK specified on PATH interferes the build.
My steps to fix the issue (in `x64 Native Tools Command Prompt for VS 2019`):
1. `SET PATH=path\to\your\maven\bin\folder` // clearing the PATH and optionally setting path to Maven bin folder 
2. `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat` // setting MS specific vars
3. `mvn gluonfx:build`

**Comment by jperedadnr** [comment]
`%PATH%` should be managed carefully, indeed... Not sure if this can be done by the plugin though.
