### ISSUE TITLE
iOS Keyboard does not close on clicking outside Text Field

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/gluonfx-maven-plugin#345]
![image](https://user-images.githubusercontent.com/25760501/122352172-7ddd3a00-cf6c-11eb-88ad-d302e5ae6496.png)

the "next" button is ""under"" the keyboard.

on iPad, there is a dedicated key in the keyboard to close it, but its not there in iOS. Moreover, clicking outside the text field does not help either - the keyboard remains there

**Comment by jperedadnr** [comment]
You can use the `KeyboardService` from Gluon Attach, it will move the view up so you can see the button.

**Comment by rnayabed** [comment]
> You can use the `KeyboardService` from Gluon Attach, it will move the view up so you can see the button.

Tried it, but it looks like the KeyboardServie is quite unstable at the moment. If you rotate the device frequently it messes the entire thing (sometimes just blank screens).

**Comment by jperedadnr** [comment]
Related https://github.com/gluonhq/attach/issues/291.
