### ISSUE TITLE
transitive "runtime" dependencies are not included

### ISSUE THREAD

**Issue by kristofdho** [gluonhq/gluonfx-maven-plugin#347]
I have a project with transitive dependencies which are marked as `runtime`. These dependencies do not make it on the `-imagecp` of the native-image call.

It looks like they are not included in the returned collection of `project.getArtifacts()` here:
https://github.com/gluonhq/gluonfx-maven-plugin/blob/231a9589f0eb9b17fa8fdffd9c1a73c48954bf27/src/main/java/com/gluonhq/NativeBaseMojo.java#L219

The documentation of that call states:
`Contents are lazily populated, so depending on what phases have run dependencies in some scopes won't be included`
So maybe that has something to do with it?

I have no idea what a fix would look like, so sadly I can't provide a PR on the matter.

**Comment by jperedadnr** [comment]
Are you running the latest plugin (1.0.1)?
We fixed that a while ago:
https://github.com/gluonhq/gluonfx-maven-plugin/blob/master/src/main/java/com/gluonhq/NativeBaseMojo.java#L249

**Comment by kristofdho** [comment]
Yes with 1.0.1.

The case seems to be:
gluonfx build project -> compile dependency -> runtime dependency

A direct runtime dependency does get included, a transitive runtime dependency doesn't. I threw together a quick example showcasing the issue: https://github.com/kristofdho/transitive-deps-gluonfx. Run instructions are included in the readme.

**Comment by jperedadnr** [comment]
Should be fixed with #368. Feel free to reopen otherwise.
