### ISSUE TITLE
Link failure on sample project with GraalVM-gluon-21.2.0

### ISSUE THREAD

**Issue by krazilek** [gluonhq/gluonfx-maven-plugin#348]
I'm receiving error when building native image of sample project, during link phase:

net.lib(DefaultProxySelector.obj) : error LNK2019: unresolved external symbol __imp_WinHttpOpen referenced in function Java_sun_net_spi_DefaultProxySelector_init
net.lib(DefaultProxySelector.obj) : error LNK2019: unresolved external symbol __imp_WinHttpGetProxyForUrl referenced in function Java_sun_net_spi_DefaultProxySelector_getSystemProxies
net.lib(DefaultProxySelector.obj) : error LNK2019: unresolved external symbol __imp_WinHttpGetIEProxyConfigForCurrentUser referenced in function Java_sun_net_spi_DefaultProxySelector_getSystemProxies

Compile and link logs are attached.

**Project code** - gluon-samples-master\HelloFXML
**OS** - Windows 7 Ultimate x64 with SP 1
**Windows SDK components** -
Windows Universal C Runtime  
C++ Build Tools core features  
MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.28)  
C++ CMake tools for Windows  
Windows Universal CRT SDK  
C++ Universal Windows Platform runtime for v142 build tools  
Windows 10 SDK (10.0.19041.0)  
**Java runtime** -
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T11:58:13+04:00)
Java version: 11.0.11, vendor: GraalVM Community
Java home: E:\work\graalvm-svm-windows-gluon-21.2.0-dev
[process-compile-1624096997685.log](https://github.com/gluonhq/gluonfx-maven-plugin/files/6680470/process-compile-1624096997685.log)
[process-link-1624096998366.log](https://github.com/gluonhq/gluonfx-maven-plugin/files/6680471/process-link-1624096998366.log)

Same error occurs on Windows 10 Enterprise x64 with same build "GraalVM CE Gluon **21.2.0**-dev-20210618_1215". 
Could not check with previous build "GraalVM CE Gluon **21.1.0**-dev-20210412_1722" - on automatic native-image installation (gu.cmd --jvm install native-image) received "Error: Unsupported Graal VM version: 21.1.0-dev"

**Comment by johanvos** [comment]
Thanks for reporting. The cause is determined (we need to add a win-http lib) and a fix will be available soon.

**Comment by krazilek** [comment]
Build "GraalVM CE Gluon 21.2.0-dev-20210621_1207" - same error

**Comment by jperedadnr** [comment]
The issue was already fixed in Substrate, but until a new release is published, you can use the plugin version 1.0.2-SNAPSHOT, by adding this repository to the pom:
```
<pluginRepositories>
        <pluginRepository>
            <id>sonatype</id>
            <url>http://oss.sonatype.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>
```

and then build again.

**Comment by krazilek** [comment]
@jperedadnr thanks for reply, gluon plugin v1.0.2-SNAPSHOT works fine - tested on sample projects "HelloFX" and "HelloFXML". 

I should also mention that "GraalVM CE Gluon 21.1.0-dev-20210415_0700" release built mentioned projects without error (with gluon plugin v1.0.1) - seems that some kind of regression occurred in Substrate. 

Closing this issue and moving to build my work application.

**Comment by jperedadnr** [comment]
There was no regression, just new requirements on Windows due to changes from GraalVM 21.1-dev to 21.2-dev.
