### ISSUE TITLE
Overriding javafxStaticSdkVersion is not user friendly

### ISSUE THREAD

**Issue by kristofdho** [gluonhq/gluonfx-maven-plugin#359]
It is not clear what the supported values are for the `javafxStaticSdkVersion` option. Almost any version I try to configure, results in a 404 status code while trying to download the zip.

Given that the current default value is `17-ea+11` according to the [documentation](https://docs.gluonhq.com/#_configuration), I assumed that the expected value would be the same as the versions on maven (https://search.maven.org/artifact/org.openjfx/javafx) which is not the case, looking at the content of my .gluon folder.

At the very least I would want to specify stable versions so running from jars locally gives the same behaviour as running the native-image. We have already run into some unexpected changes because it defaults to the one of the latest early access builds,  and we would want to avoid that.

**Comment by johanvos** [comment]
Good remark. Currently, we aim to build all platforms whenever a tag is created in the OpenJFX repository, including the static libs.

**Comment by kristofdho** [comment]
Had some time to try it out. The repository tags don't seem to work, but adding a `-ea` to them, eg `17+18` -> `17-ea+18` does work.
I previously always assumed that the `ea` stood for early access, which doesn't seem to be the case. It would be very helpfull to have some extra documentation clarifying all of this.
