### ISSUE TITLE
MojoExecutionException: Packaging failed

### ISSUE THREAD

**Issue by Raghav-Deo** [gluonhq/gluonfx-maven-plugin#369]
I was trying to package an app for android platform.The build command runs fine but this exception occurs while trying to package for android.
Caused by: org.apache.maven.plugin.MojoExecutionException: Packaging failed
    at com.gluonhq.NativePackageMojo.execute (NativePackageMojo.java:55)

**Comment by abhinayagarwal** [comment]
Hi,

Can you attach the logs from `target/gluonfx/x86_64-web/gvm/log/` ?

**Comment by Raghav-Deo** [comment]
Sorry but I have already switched to a different technology. I will be closing thing issue now.
