### ISSUE TITLE
Severe blinking/glitchy screen when using On Screen keyboard [aarch64] [DRM/KMS]

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/gluonfx-maven-plugin#386]
This is a weird one. when using standard JavaFX jmods + JVM, the on screen keyboard works perfectly fine on the aarch64/arm32 platform.

However, when using the gluonfx plugin (native image) for aarch64, the entire screen starts blinking only when using the On Screen Keyboard. It works completely fine otherwise!

Here is a video demonstrating the problem in the native image for Stream-Pi Client. As you can see, the app behaves properly as its supposed to when not using the On screen keyboard. However, just when a text field is clicked and the on screen keyboard is called, it starts glitching. Also, when you close the onscreen keyboard, the problem does not happen anymore.

Interestingly, this does NOT happen when using in X11 mode

https://user-images.githubusercontent.com/25760501/141692847-779e59da-33fb-4356-a628-82c5285fc918.mp4

**Comment by jperedadnr** [comment]
Can you try adding `-Duse.egl=true`?

**Comment by rnayabed** [comment]
Sure. Will try it out asap

**Comment by rnayabed** [comment]
And it works! Adding `-Duse.egl=true` during runtime fixes this issue. Shouldn't this be turned on by default?
