### ISSUE TITLE
Locale defaulting to en_US on Android

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/gluonfx-maven-plugin#389]
Locale always defaulting to en_US even if device locale is en_IN or something else.

**Comment by jperedadnr** [comment]
See https://www.graalvm.org/reference-manual/native-image/Resources/#locales

By default, only en_EN locale is included when building the native image. 

You can modify that to your convenience with:
```
<nativeImageArgs>
    <arg>-H:IncludeLocales=en,en-IN</arg> // your list of locales
 <!-- <arg>-H:+IncludeAllLocales</arg> --> // all possible locales, but bigger size
</nativeImageArgs>
```

Also you can use `<arg>-H:DefaultLocale=en-IN</arg>` for instance, if you want to set a default locale different than the en_EN.

**Comment by rnayabed** [comment]
Thank you.
