### ISSUE TITLE
link failed on amd64

### ISSUE THREAD

**Issue by 408509165** [gluonhq/gluonfx-maven-plugin#391]
Version : GraalVM 22.0.0-dev Java 11 CE (Java Version 11.0.13+8-jvmci-22.0-b02)

**Comment by 408509165** [comment]
Link command error -> link: extra operand 'j2pkcs11.lib'
this is command :
link F:\my\DmTest\target\gluonfx\x86_64-windows\gvm\DmTest\launcher.obj F:\my\DmTest\target\gluonfx\x86_64-windows\gvm\tmp\SVM-1638252926097\org.example.app.obj j2pkcs11.lib java.lib net.lib nio.lib prefs.lib fdlibm.lib sunec.lib zip.lib jvm.lib libchelper.lib advapi32.lib iphlpapi.lib secur32.lib userenv.lib version.lib ws2_32.lib winhttp.lib /NODEFAULTLIB:libcmt.lib /SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup comdlg32.lib dwmapi.lib gdi32.lib imm32.lib shell32.lib uiautomationcore.lib urlmon.lib winmm.lib glass.lib javafx_font.lib javafx_iio.lib prism_common.lib prism_d3d.lib /WHOLEARCHIVE:glass.lib /WHOLEARCHIVE:javafx_font.lib /WHOLEARCHIVE:javafx_iio.lib /WHOLEARCHIVE:prism_common.lib /WHOLEARCHIVE:prism_d3d.lib /OUT:F:\my\DmTest\target\gluonfx\x86_64-windows\DmTest.exe /LIBPATH:C:\Users\Administrator\.gluon\substrate\javafxStaticSdk\18-ea+6\windows-x86_64\sdk\lib /LIBPATH:E:\graalvm-svm-windows-gluon-21.2.0-dev\lib\svm\clibraries\windows-amd64 /LIBPATH:E:\graalvm-svm-windows-gluon-21.2.0-dev\lib\static\windows-amd64

Even though the folder  is "graalvm-svm-windows-gluon-21.2.0-dev " ,the real version i use is 22.0.0

I've tried replacing 'j2PKcs11.lib' with static full path and it still doesn't work.

**Comment by jperedadnr** [comment]
Some questions:
- Plugin version (make sure you use the latest)
- GraalVM version (the actual one, make sure you have set and use only one)
- Post your full logs
- How to reproduce? 
- Does HelloFX work?

**Comment by chirontt** [comment]
About the HelloFX sample app, I've seen the link errors for it in Linux (Ubuntu), but not in Windows. The errors occur for both JDK11 and JDK17 versions of the GraalVM 21.3.0, although the errors are different for each JDK version. The steps to reproduce are simple:

- clone the `gluonfx-samples` [repo](https://github.com/gluonhq/gluon-samples) from GitHub
- `cd gluonfx-samples/HelloFX`
- run the HelloFX app with the agent: `mvn gluonfx:runagent`
- then build its native image with: `mvn gluonfx:build`

In Windows, the above steps work fine in both JDK11 and JDK17 versions of GraalVM 21.3.0, producing good working native images. But in Linux (Ubuntu) the last step fails during the link stage, in both JDK versions.

For the `JDK11` version, the link errors are:
```
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x98)
: undefined reference to `Java_com_sun_pisces_PiscesRenderer_clearRectImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x2a0
): undefined reference to `Java_com_sun_pisces_Transform6_initialize'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x400
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_drawImageImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x4d0
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_emitAndClearAlphaRowImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x560
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_fillRectImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x570
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_setCompositeRuleImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x9b0
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_initialize'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0xa98
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_setLinearGradientImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0xb60
): undefined reference to `Java_com_sun_pisces_AbstractSurface_disposeNative'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0xb70
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_setTextureImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0xb88
): undefined reference to `Java_com_sun_pisces_AbstractSurface_getRGBImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0xd68
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_setRadialGradientImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0xe08
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_disposeNative'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0xed8
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_setClipImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0xfd0
): undefined reference to `Java_com_sun_pisces_PiscesRenderer_setColorImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x12c
0): undefined reference to `Java_com_sun_pisces_PiscesRenderer_fillLCDAlphaMaskImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x12f
0): undefined reference to `Java_com_sun_pisces_PiscesRenderer_setLCDGammaCorrectionImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x14a
8): undefined reference to `Java_com_sun_pisces_PiscesRenderer_fillAlphaMaskImpl'
/usr/bin/ld: /home/tue/dev/javafx/gluon-samples/HelloFX/target/gluonfx/x86_64-linux/gvm/tmp/SVM-1640907160009/hellofx.hellofx.o:(.data+0x14e
0): undefined reference to `Java_com_sun_pisces_JavaSurface_initialize'
collect2: error: ld returned 1 exit status
```
And for the `JDK17` version of GraalVM 21.3.0, the link errors are (much shorter):
```
/usr/bin/ld: cannot find -l:libsunec.a
collect2: error: ld returned 1 exit status
```

**Comment by 408509165** [comment]
sorry,I can't find the project and can't provide detailed reproduction methods and environment version requirements, so please close this issue.

**Comment by tcsnzh** [comment]
I resolve it , maybe ...

https://github.com/gluonhq/gluonfx-maven-plugin/issues/314#issuecomment-991661882
