### ISSUE TITLE
How to set minSdkVersion on Android app

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/gluonfx-maven-plugin#422]
I tried to set this parameter in the Android manifest, but the task nativePackage failed. So, Where I set this configuration?

**Comment by jperedadnr** [comment]
Did you follow https://docs.gluonhq.com/#platforms_android_distribution_manifest ?

**Comment by websystemtechnology** [comment]
Yes, Maybe I'm wrong something; I'll try to explain what I do:

I modified src/android/AndroidManifest.xml wit this 

<uses-sdk android:minSdkVersion="28"
          android:targetSdkVersion="30" />
          
when I execute ./gradlew --info nativePackage the error is this:





I try to insert the property in the build.gradle  (and remove in the manifest)  the error in this time is:

Caused by: com.android.builder.errors.EvalIssueException: Failed to parse XML in /home/ws/eclipse-workspace/gfx_app_elvid/build/gluonfx/aarch64-android/gvm/android_project/app/src/main/AndroidManifest.xml
  The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
  	at com.android.builder.errors.IssueReporter.reportError(IssueReporter.kt:107)
  	at com.android.builder.errors.IssueReporter.reportError$default(IssueReporter.kt:103)


Could not set unknown property 'minSdk' for ReleaseConfiguration{packageType=null, description='null', vendor='null', version='null', macAppStore=false, macSigningUserName=null, macAppCategory=null, bundleName='null', bundleVersion='null', bundleShortVersion='null', providedSigningIdentity='null', providedProvisioningProfile='null', skipSigning=false, simulatorDevice='null', appLabel='null', versionCode='null', versionName='null', providedKeyStorePath='null', providedKeyStorePassword='null', providedKeyAlias='null', providedKeyAliasPassword='null'} of type com.gluonhq.gradle.ReleaseConfiguration.

**Comment by jperedadnr** [comment]
(I see that you are using gradle, then this should be filed under the GluonFX gradle plugin.)

Then you need to manually do the package step:

- remove the `src/android/AndroidManifext.xml` file
- run `./gradlew nativePackage` (I assume you already did `./gradlew nativeBuild`)
then 
- cd `build/gluonfx/aarch64-android/gvm/android_project/`
- edit the file `app/build.gradle` and modify the version there:
```
android {
...
    defaultConfig {
        minSdkVersion 21 // <----
        targetSdkVersion 30
...
    }
...
} 
```
- save and then run:
```
export ANDROID_SDK_ROOT=~/.gluon/substrate/Android
./gradlew app:assembleDebug 
cd ../../../../../
./gradlew nativeInstall nativeRun 
```

**Comment by websystemtechnology** [comment]
It's ok. Now I can create apk.
Do You think think that this parameter is added into the gradle plugin?

**Comment by jperedadnr** [comment]
what parameter? the min sdk?

**Comment by websystemtechnology** [comment]
Sorry for delay, I tested several device; I verify that can I istall my app in Android 7; now I have some device dosn't permit to istall the app. Can ypu help me to undestand the cause?
Device model: redmi 9c -Android 10 
In the store I recive this message: "Il tuo dispositivo non è compatibile con questa versione"

**Comment by garywhittington** [comment]
Concerning the original question, how is it possible to set the minSdkVersion within a POM file?   I have tried adding it to the properties and releaseConfiguration but without luck (and I could not find any examples in documentation).
