### ISSUE TITLE
Can Android Apk be build without the need of GraalVM (JDK only)?

### ISSUE THREAD

**Issue by ctoabidmaqbool** [gluonhq/gluonfx-maven-plugin#440]
As still some of major Java libraries are not yet fully ready for GrallVM native image feature, so Can I make Android Apk without GrallVM?

E.g. One of my major java librariy FlywayDb is not yet ready for GrallVM native image feature! I am waiting for a such nice feature form almost one year still not get it up.

So how can I make Android APK by using latest gluonfx plugin?

Note: Old javafx-mobile-plugin can be used to make android apk with old flyway version. But That's plugin is very old have many issues e.g. plugin can't be used with jdk 11+ and apk can't be run on Android 11.

Any solutions form you?

**Comment by jperedadnr** [comment]
The GluonFX plugin leverages GraalVM to create a native image for Android, so there is no other way. 
As you mentioned, the old JavaFXPorts plugin could be still used, but it is EOL and no longer maintained or upgraded.
