### ISSUE TITLE
How gluonfx-maven-plugin modify pc-application-exe  icon?

### ISSUE THREAD

**Issue by wonderfulLand** [gluonhq/gluonfx-maven-plugin#442]
How gluonfx-maven-plugin modify pc-application-exe  icon?

**Comment by Hugolarson** [comment]
Put it in \src\windows\assets\icon.ico
I think there should be a way to skip icon or define it in build script

**Comment by UndeadDevel** [comment]
Note: it would be nice if the log said that, i.e. that the icon needs to be in \src\windows\assets and not just \src\windows because the latter is what the log says and it doesn't work.
