### ISSUE TITLE
Current GraalVM version not supported

### ISSUE THREAD

**Issue by UtilFunction** [gluonhq/gluonfx-maven-plugin#474]
Graal has changed its versioning and it's causing problems for the plugin.
```
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.18:compile (default-cli) on project fxproject: Error: Current GraalVM version (17.0.7) not supported.
[ERROR] Please upgrade to 22.1 or higher
```

**Comment by jperedadnr** [comment]
Fixed with https://github.com/gluonhq/substrate/pull/1222

It can be tested with plugin 1.0.19-SNAPSHOT using `<pluginRepository/>` with url http://oss.sonatype.org/content/repositories/snapshots/

**Comment by mipastgt** [comment]
This brings up the question again whether it is actually allowed/reccommended to use the latest GraalVM with the Gluon plugin. The documentation still states:
`[...] to create native-images for your Gluon application, you will need the latest version of the Gluon built version of GraalVM.` which is still `GraalVM CE Gluon 22.1.0.1-Final` from 2022-06-08.
So, does Gluon recommend and support the latest official GraalVM version and is it now fully compatible with JavaFX and the tooling or not?

**Comment by jperedadnr** [comment]
Indeed, to use the GluonFX plugins, the GluonFX docs recommend the Gluon's GraalVM build https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final
which is mostly needed for the mobile targets, while on desktop, the official GraalVM build could be used as well. 

However, there's no guarantee that any new change in the official build is immediately supported by the GluonFX plugins.

**Comment by HaneneS** [comment]
Hi @jperedadnr is the GRAALVM for linux working for the architecture aarch64?

thank you
