### ISSUE TITLE
Error on link goal

### ISSUE THREAD

**Issue by R0land013** [gluonhq/gluonfx-maven-plugin#496]
Hi there. I was trying to generate a native image of my app https://github.com/R0land013/showly-desktop . When I execute the `mvn clean gluonfx:build` command all executes normally till the link goal starts to run, then the build fails and the following errors are shown in the `link` goal execution.
![Screenshot from 2023-12-19 18-08-00](https://github.com/gluonhq/gluonfx-maven-plugin/assets/58601896/7b007e04-d56e-4bfa-b814-7f779ff9cc73)
I am using Ubuntu 22.04.3 LTS, and I am following all the requirements to use gluonfx-maven-plugin. I have spent several days on this problem.

**Comment by taranion** [comment]
Had the same problem: https://github.com/gluonhq/substrate/issues/1169

Basically making use of code from "java.awt" is not fully supported, it seems.

**Comment by R0land013** [comment]
Wow that fixed my problem! The first attempt did not work because I had JAVA_HOME pointing to my JDK 17 path and link goal could not find the ${java.home}/lib/static/linux-amd64/glibc/libmlib_image.a . So I changed the JAVA_HOME to point to the same path as GRAALVM_HOME, and it worked. Thank you very much. I will close this issue.
