### ISSUE TITLE
Support for Maven 3.9.0 or newer

### ISSUE THREAD

**Issue by badvision** [gluonhq/gluonfx-maven-plugin#506]
Currently support for Maven is limited to v3.8.8, but it's getting increasingly more difficult to support that in local build environments.  For example, Homebrew formulas force upgrades well past 3.9.0 for maven now.

**Comment by kristofdho** [comment]
This should (in theory) only require bumping the maven resolver plugin version:
https://github.com/gluonhq/gluonfx-maven-plugin/blob/cf26b56a9071aa93b4b7f9b4b5e18f966278bdce/pom.xml#L50
1.7.3 is already pretty old, and a v2 is even already available.
