### ISSUE TITLE
Compile step fails when trying to download JavaFX static libs

### ISSUE THREAD

**Issue by 12bPilot** [gluonhq/gluonfx-maven-plugin#517]
Downloaded latest Gluon compiled GraalVM for MacOS (https://github.com/gluonhq/graal/releases/download/gluon-23%2B25.1-dev-2409082136/graalvm-java23-darwin-aarch64-gluon-23+25.1-dev.tar.gz).
Using IntelliJ and the GluonFX Maven plugin (downgraded maven version to 3.8.8), the compile step aborts during downloading of JavaFX static libs.
Here is the output:
```
Mon Sept 23 18:54:16 CEST 2024][INFO] We will now compile your code for arm64-apple-ios. This may take some time.
[Mon Sept 23 18:54:16 CEST 2024][FINE] Processing JavaStatic dependencies at /Users/xyz/.gluon/substrate/javaStaticSdk/24-2/ios-arm64/lib
[Mon Sept 23 18:54:16 CEST 2024][FINE] Checking java static sdk hashes
[Mon Sept 23 18:54:16 CEST 2024][FINE] Processing JavaFXStatic dependencies at /Users/xyz/.gluon/substrate/javafxStaticSdk/24-ea+5/ios-arm64/sdk/lib
[Mon Sept 23 18:54:16 CEST 2024][INFO] Downloading JavaFX static libs...
[Mon Sept 23 18:54:16 CEST 2024][FINE] Processing zip file: url = https://download2.gluonhq.com/substrate/javafxstaticsdk/openjfx-24-ea+5-ios-arm64-static.zip, zip = /Users/xyz/.gluon/substrate/openjfx-24-ea+5-ios-arm64-static.zip, subDir = javafxStaticSdk, levels = [24-ea+5, ios-arm64], md5 = javafxStaticSdk-ios-arm64.md5
[Mon Sept 23 18:54:17 CEST 2024][SEVERE] Downloading failed: Server returned HTTP response code: 403 for URL: https://download2.gluonhq.com/substrate/javafxstaticsdk/openjfx-24-ea+5-ios-arm64-static.zip
```

Fails with HTTP response code 403.
Why is the access denied?

**Comment by ctoabidmaqbool** [comment]
@12bPilot MAKE SURE YOU ARE USING LATEST GRAALVM BY GLUON
E.G.
https://github.com/gluonhq/graal/releases/tag/gluon-23%2B25.1-dev-2409082136

![image](https://github.com/user-attachments/assets/84e95c29-ca6f-4533-877d-c63168613138)

AND STATIC gluon plugin e.g. `1.0.24` not snapshot one!

**Comment by 12bPilot** [comment]
Solved, my bad.
In my pom.xml, there was still an old option <javafxStaticSdkVersion> defined. Removing this caused the plugin to download the default static JavaFX SDK.
