### ISSUE TITLE
Specify platform specific arguments via the plugin

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/gluonfx-maven-plugin#99]
There are many platform specific arguments that should be specified via the plugin. For example, in case of Android, a user needs to specify the `package` which acts as an identifier for the app. Similarly, iOS needs `AppID`.

User should be able to pass these arguments to the platform via the plugin configuration.

An example of such configuration can be as follows:
```
<plugin>
    <groupId>com.gluonhq</groupId>
    <artifactId>client-maven-plugin</artifactId>
    <version>${client.plugin.version}</version>
    <configuration>
        <mainClass>${mainClassName}</mainClass>
        <target>android</target>
        <android>
            <package>com.gluonhq.example</package>
        </android>
    </configuration>
</plugin>
```

**Comment by tiainen** [comment]
We should carefully consider the target specific configuration properties. If they are usable on other targets, they should probably not live in a specific configuration section.

For instance, I can image that the id of a project can be used for other targets as well. Hence having an identifier field would be more desirable:

    <identifier>com.gluonhq.example</identifier>

`${project.groupId}` might be used as the default value. Similarly, we can define a `<version>` to specify the version of the target package.

**Comment by johanvos** [comment]
We really need to avoid platform-specific configuration settings as much as possible. We are doing Java, which is cross-platform by nature, and should keep that spirit as far as possible in the configuration as well.

**Comment by mipastgt** [comment]
It might also be useful to have a look at already existing tools like jpackage and jlink and see what naming converntions they have adopted. Some consistency between Java tools doesn't hurt.

**Comment by abhinayagarwal** [comment]
`jpackage` allows you to pass different identifiers for different platforms. For example, it has both `--mac-package-identifier` and `--linux-package-name`.

Using a default identifier sounds like a good idea. A combination of `groupId` and `artifactId` for the package name and bundle id in Android and iOS respectively, sounds like a good idea. However, this is just one case we are looking at right now. There are so many platform specific properties which are not shared by any other platform.
